sonar.projectKey=jimi-117_glowup_frontend
sonar.organization=jimi-117
sonar.host.url=https://sonarcloud.io

sonar.sources=src

sonar.exclusions=**/node_modules/**, **/build/**, **/dist/**, **/*.spec.js, **/*.test.js

sonar.sourceEncoding=UTF-8

# Tests codes                                           # TODO: Enable when test sources are available
# sonar.tests=src
# sonar.test.inclusions=**/*.spec.js, **/*.test.js

# Test coverage
# sonar.javascript.lcov.reportPaths=coverage/lcov.info